### ISSUE TITLE
First Sprint cc/ minhchau273

### ISSUE THREAD

**Issue by mceraso** [FordhamMuseumApp/SwiftRepo#24]
Hi Chau,

cc/ @minhchau273

Please see our first sprint underneath the "dev" branch. If you download the app, you will not be able to get the images because we are operating with a special Wifi point within the museum. There is a gif that shows you where we are.

All best!
Michael Ceraso and team

**Comment by minhchau273** [comment]
:+1: Great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.
Good to see that you have already started adding UI polish to your app. :star2:

**Comment by mceraso** [comment]
Thank you @minhchau273 ! We're really excited about it. What date should we have the MVP in by? We've been adding polish along the way but may need to adjust our process given a 2 week timeline.
